name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: [ "bug" ]
body:
- type: markdown
  attributes:
    value: |
      Thanks for reporting a bug! Please provide as much detail as possible.

- type: textarea
  id: description
  attributes:
    label: Bug Description
    description: A clear description of what the bug is
    placeholder: Describe the bug...
  validations:
    required: true

- type: textarea
  id: reproduction
  attributes:
    label: Steps to Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Configure .env with...
      2. Run ./run.sh
      3. See error...
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: What you expected to happen
  validations:
    required: true

- type: textarea
  id: environment
  attributes:
    label: Environment
    description: |
      Provide details about your environment:
    placeholder: |
      - OS: [e.g. macOS, Windows, Linux]
      - Python version: [e.g. 3.9.0]
      - Azure Front Door type: [Standard/Premium]
      - Number of endpoints: [e.g. 1, 3, etc.]
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Error Logs
    description: If applicable, add error logs or screenshots
    render: shell
